### ISSUE TITLE
Notification range

### ISSUE THREAD

**Issue by thatvalis** [pompobit/ScanGO#1]
Hi, the app seems to work great after testing today. However, I was wondering if you could make more choices for the notification range available? Right now the max is 150m, but it would be nice if you could add options of maybe 250, 500, 750 and 1000m? 
Also, another suggestion would be to have an option in settings to chose where clicking the status bar notification will take you. Right now it opens the app, but having an option of going directly to Google maps navigation would be great. Keep up the good work!

**Comment by Borech** [comment]
Icons and range please

**Comment by fouadal** [comment]
Hello, first of all very nice app and works good when there is no problems with the server (you cant do anything about it). What i want to ask is why do i get a parsing error when i want to install it on android radio/gps in the car, would be very nice if i could install it on there to drive where the pokemons are without using my phone? Thankyou
