### ISSUE TITLE
No pokemon with FastPokeMap

### ISSUE THREAD

**Issue by ELynx** [pompobit/ScanGO#10]
v1.21, using FastPokeMap
location is [Google Maps](https://www.google.ru/maps/@59.963191,30.3129678,16z)
I check fastpokemap site and see pokemons on the map
I see them in the PoGo app too
During single scan I see hex cells turn yellow/blue->green, but no pokemon appear

**Comment by pompobit** [comment]
Are you sure you haven't enabled filters for those pokemon?
I just checked your location and it works ad always
![screenshot_20160919-133404](https://cloud.githubusercontent.com/assets/6191771/18630741/ad5839e6-7e6e-11e6-8dac-2843c4bbdf82.png)

**Comment by ELynx** [comment]
![screenshot_2016-09-19-15-16-48](https://cloud.githubusercontent.com/assets/1621251/18631700/2ec01fbe-7e7c-11e6-8c59-567aa32a235c.jpg)
Works now, thank you!
Don't know what the reason was before.
