### ISSUE TITLE
IV moveset implementation ?

### ISSUE THREAD

**Issue by abhinav91690** [pompobit/ScanGO#11]
Is it possible to implement ivs or movesets?

**Comment by pompobit** [comment]
Hi, unfortunately it is not possible to get IV and specific pokemon information without login and simulate an encounter.
If some of the services I use will introduce these info, I'll do it too, but at the moment it is not possible without allowing the user to login, and I don't want to allow it to avoid risks of ban

**Comment by abhinav91690** [comment]
Thanks for the quick reply
