### ISSUE TITLE
Wrong notifications

### ISSUE THREAD

**Issue by torantal** [pompobit/ScanGO#18]
I have two filters:
- (a) All Pokemon, no alerts
- (b) some Pokemon, some alerts

When I run (a) erverything is fine. When I then switch to (b)  with a continuous scan running I suddenly receive alerts for Pokemon shown for (a), even though they are neither shown nor have alerts set in (b) 

Running version 1.28 with PokeStumble as the search host.

**Comment by pompobit** [comment]
Don't switch filters while a scan is ongoing. The behaviour is undefined at the moment, I'll try to fix this but with all the mess with FPM at the moment I have higher priority task to deal with

**Comment by torantal** [comment]
Sure, no problem. Perhaps an easy fix would be to automatically stop an ongoing scan before making the filter switch?

**Comment by pompobit** [comment]
yes probably I'll do that

**Comment by Yosephgratika** [comment]
Goodluck on the deal with FPM, I am willing to pay  for premium scan go services from FPM server
