### ISSUE TITLE
Application hangs frequently

### ISSUE THREAD

**Issue by blakadder** [pompobit/ScanGO#2]
The app hangs frequently with a request to close the app after a couple of minutes of the entire system being unresponsive. 

I'm using a Redmi 3 Pro running MIUI 8 (based on Android 5.1.1). What can I do to give you more information

**Comment by pompobit** [comment]
I'm not sure what is wrong with that device, anyway I'm about to release a new version v1.10).
Let me know if the issue persists once upgraded
