### ISSUE TITLE
Unable to login now

### ISSUE THREAD

**Issue by MortalMercury** [pompobit/ScanGO#3]
Since today when I try to enter in my fake Pkmn Trainer Club the app keeps loading a few times and it says it's because a name or pass wrong written (I don't think so) or a server error (Pokemon Go goes ok)
Is it s a concrete issue of mine or is it something else?
What do I do?

**Comment by pompobit** [comment]
I had some trouble to login with PTC today, probably is related to PTC servers (not Pokemon GO ones).
Can you try to kill the app and try again now? After a couple of tries I managed to login using PTC now

**Comment by pompobit** [comment]
It seems like that API changed on server side, I need to update requests to let the app to work again

**Comment by edone101** [comment]
Is there any news on the update? When do you think we can expect news?

**Comment by pompobit** [comment]
@edone101 unfortunately the changes are not so trivial, all people around the world is dealing with the new format.
I'll try to update as soon as we find a fix
