### ISSUE TITLE
Blurry images on galaxy S7

### ISSUE THREAD

**Issue by Korri** [pompobit/ScanGO#5]
Don't know if it is because of the high pixel density, but any size of importef images (tried 40x40 and 48x48) are blurry.
Screenshot: https://imgur.com/yP7tzYW

**Comment by pompobit** [comment]
yes probably your dpi is too high for those images.
Anyway some users get some issue importing the images, so I'm working to an alternative method

**Comment by pompobit** [comment]
btw while I don't find an alternative method, you could try the "type2" images, they should appear better on high density screens

**Comment by Korri** [comment]
I tried the type2, they look a bit better. There should be a way on your side to tell android not to smoothen the images out, or at least to display them at 1px = 1 screen px, they'll be small on high dpi screen, but should work with the 48x48 ones.

**Comment by pompobit** [comment]
v1.15 introduced images from url, that should scale better with high pixel density screens.
Try the urls and choose what you like more

**Comment by Korri** [comment]
Hey, Works much better! Would be cool to have some 96x96 icons reduced to 48x48 (to profit from the high res screen), but it is allready pretty good :)
