### ISSUE TITLE
Improvment of the "continuous scan"

### ISSUE THREAD

**Issue by GCHarald** [pompobit/ScanGO#6]
I like this app, because it don't need an account and it sends notifications which I can read on my Pebblewatch.
But when I use the continuous scan, the scans end after some minutes with the status "scan completed" and the app stops running in background.
In my opinon the scan mode "continious scan" should scan continiously in background and send notifiations until I stop the scan.
Is the correct or would this be a new feature.
Then it would be a nice feature because it would creates continuously notifications and it would save battery consumption.

**Comment by pompobit** [comment]
the continuous scan is intended to work as you say.
Actually if the servers are unreliable and too many requests fail, the scan stops itself. I'm working to find an alternative solution and avoid to break the scan so often

**Comment by pompobit** [comment]
version 1.16 improved scan stability a lot, give it a try ;)
